### ISSUE TITLE
Karma Decreases When Someone Shoots You and You Kill Them

### ISSUE THREAD

**Issue by omar-damaj** [Bara/TroubleinTerroristTown#179]
Is there a possibility that Karma does not get removed from a player if they were damaged by the player they killed? That way if someone shoots you and you kill them you wont get punished for that.

**Comment by PRAWKC** [comment]
I agree with this, if an innocent shoots and causes damage to you and you manage to kill them only to find out they were innocent. Then like you said, karma should not be lost for that player. @Bara20 Can we add this feature to a future build?

**Comment by danielsartor** [comment]
I was able to implement that on my TTT server in a dumb way, but it works.
I can save up to 2 players, that was hurted and those players can kill the attacker without losing karma and credits, also notifying the user that he didn't lose karma because the other innocent attacked first.

Logic implemented:
If innocent A hurted innocents B, C, D and E on the following order, only the last 2 hurted will be able to kill him without losing karma. In this case, victim 3 (D) will overwrite victim 1 (B) and victim 4 (E) overwrites victim 2 (C).

I can't commit my code because I merged the shop, dna scanner, c4/jihad and stations inside of ttt.sp also I declared player_hurt event, that is probably defined somewhere else already, and used the same detections from player_death, to check INNOCENT x INNOCENT, TRAITOR x TRAITOR and DETECTIVE x DETECTIVE. Then on player_death I could check if the victim hurted the attacker before and do not decrease the karma and credits.

The reason I merged so many plugins was due to custom !dice plugin using credits and items from shop as possible rewards depending on the role.

Let me know if you need any help to implement this on version 3, I can share that piece of code and explain what I did, so you can implement in a better way.

**Comment by danielsartor** [comment]
@Bara check Pull Request #313
