### ISSUE TITLE
immunity from punishment for RDM

### ISSUE THREAD

**Issue by Septembers** [Bara/TroubleinTerroristTown#302]
Can you add a flag for administrators who will have immunity from punishment for RDM?

**Comment by PRAWKC** [comment]
If a flag is added make sure that you can choose to enable or disable this option. Personally I do not believe that admins should have a free pass on RDM or any rule for that matter. If you are auto slayed due to the system. Ex: Killing another Traitor buddy. Then you deserve the slay(s). I think if you type /rslays <name> 0 It will stop the RDM punishment.

**Comment by Septembers** [comment]
I shot at the wall, the player jumped at the sight, in the end I was left guilty. I think this is wrong)

**Comment by Septembers** [comment]
And there are many such examples

**Comment by popey456963** [comment]
Sorry, forgive me if I'm wrong, but don't administrators already have to type `/rslays 1` or something similar in order to slay you for an RDM?

**Comment by PRAWKC** [comment]
My initial post and this one is not meant to argue about it. If this get added then if no flag is specified nobody gets immunity. Also it should be disabled by default.

@Septembers I understand that their are rare circumstances where this issue can occur. I rather the admin take the loss then give immunity.  In my opinion when you know you have immunity from this then you will start to do risky plays since you know their is no consequence. Also I believe in fair play, if a player will get slayed for it then so should admins their should be no immunity. If you get auto slayed its for bad action, even if it was an accident you still messed up the round for someone, so you should loose out on the next round. That is just my opinion though.

In your situation you said "I shot at the wall" was their a specific reason for shooting the wall? or were you randomly just shooting a wall and someone walked into it? 

@popey456963 Yes they do but I believe the OP is talking about the configs found in ttt.cfg such as "ttt_punish_innocent_for_rdm_kils" or "ttt_punish_traitor_for_rdm_kils" etc. Depending on how you configured it, then players would be auto slayed.

**Comment by Bara** [comment]
I'm not very convinced with this suggestion, but we could add an forward to handle it.

**Comment by Bara** [comment]
I've added TTT_OnPlayerDeath as forward. Commit coming soon...
