### ISSUE TITLE
Why Innocent can't slay other Innocent when they got RDM?

### ISSUE THREAD

**Issue by superblack4** [Bara/TroubleinTerroristTown#315]
So basically the main point i want to talk about is that when a Traitor RDM other Traitor, they got the option to punish or forgive. This happen for Detective vs Detective and Innocent kill a Detective too. However, why the menu is not appear for Innocent to forgive/punish other Innocent for RDM? Are there any solution or plugin to decrease HP the attacker about 50HP or 100HP?

**Comment by Bara** [comment]
I don't added/changed this part, because I never played TTT on a public server. Maybe @good-live or anyone?

**Comment by good-live** [comment]
Wenn also don't use that feature. Im ging to take a look in the code and figure it out, but I guess that's still some of the code taken from Francisco :D

**Comment by good-live** [comment]
Yeah that's pretty much old code. To be honest i would prefer removing it as it doesn't really makes sense. We can't detect if a kill was a RDM or not and on a usual public server people are going to slay the other one always.

@superblack4 Any specific reason why you are using that feature?

**Comment by superblack4** [comment]
@good-live Yes i do have. Many of my player are complaint about RDM between each Innocent when about 45% of them cannot understand the rule even I have explain very carefully and force them to read the fule before play TTT. Also, Detectives are sometime randomly shoot other people (include Traitors) even they don't find any evidence or saw them killing other people at the beginning of the match. I think you and Bara should consider about this and add the features (maybe other people will turn off this option). Anyway thank you so much for looking about this problem.
Best wishes and good luck

**Comment by good-live** [comment]
I don't doubt that many players are RDM'ing. The core problem that i have with this feature is that there's no chance to determine wether it was an RDM or not, because that relates to situational stuff. On my server it's disabled for that reason, because people were always like "THAT WAS AN RDM, SLAY THAT PERSON INSTANTLY" although he had good reasons to kill him. 

Well but if you really need that feature, so your players can abuse it :P
It shouldn't be hard to add a innocent-innocent check (i also don't understand why that's not done already)

@Bara Do you know why it's checking if the victim was holding a prop or had a silenced Weapon? https://github.com/Bara/TroubleinTerroristTown/blob/master/addons/sourcemod/scripting/ttt/ttt.sp#L1863

Is that some kind of bad legit kill detection?

**Comment by superblack4** [comment]
@good-live How can I add a innocent-innocent check? Any solution ✌️

**Comment by Bara** [comment]
I don't know why, but it's included since [beginning](https://github.com/Bara/TroubleinTerroristTown/blob/4036bda34f9bbb9b4b68eb359075ddb6eea3f72c/addons/sourcemod/scripting/ttt.sp). I think it's was added with the [RDM Detection from SlayersGaming](https://github.com/Bara/TroubleinTerroristTown/blob/master/CREDITS.md#previous-developersauthors-of-useful-plugins). Our code based partailly on the SlayersGaming fork

**Comment by good-live** [comment]
Okay im going to remove that and add a innocent-innocent check. For the future this should be moved into a seperate plugin.

**Comment by superblack4** [comment]
@good-live  Thank you so much for your effort 👍 
Hope u will release that plugin soon

**Comment by good-live** [comment]
@superblack4 can you test the recent changes and report back?

**Comment by superblack4** [comment]
@good-live Which changes sir?

**Comment by good-live** [comment]
The latest two commits by me

**Comment by superblack4** [comment]
Which one @good-live ? The first one, second one or both?

**Comment by superblack4** [comment]
I will give a try tommorow and tell you the result. Thank you so much for your effort @good-live  :)

**Comment by good-live** [comment]
As i already said i think it's a dumb feature so im not going to put anymore effort into it. 

Happily it should be easy to move this into an extra plugin and add some stuff.
So anybody can do it :)

**Comment by superblack4** [comment]
@good-live I know what are you thinking and personally I am agree with your idea. However, many players in my server are complaining about RDM so I have to ask for help. BTW thx you so much for your effort :)

**Comment by Bara** [comment]
@good-live 👍 
Before we add new features to RDM Manager, it should extract out of the core plugin.
