### ISSUE TITLE
Body found spam

### ISSUE THREAD

**Issue by danielsartor** [Bara/TroubleinTerroristTown#396]
SourceMod 1.10.0.6356
Metamod 1.11 - build 1116
TTT Commit 2012(SM 1.10)

![image](https://user-images.githubusercontent.com/1349833/49224226-9d68e300-f3bf-11e8-818e-3a53e02ee198.png)

**Comment by Bara** [comment]
@danielsartor Can you test it with SM1.9 and/or with TTT 1.9 Build? I had tested it with 1.9 (both) and works fine. Maybe it's related to SM1.10.

**Comment by danielsartor** [comment]
Yep, it was related to SM 1.10. I am testing a new version of 1.10 and I will check if this issue persists.

**Comment by Bara** [comment]
1474 works fine and 1583 doesn't work.

**Comment by Bara** [comment]
I recompiled the latest TTT version with SourceMod 1.10.6250 and it works fine. TTT 1535 was also compiled with 1.10.6250 and TTT 1536 with 1.10.6255 and TTT 1536 doesn't work without any changes in the ragdoll part.

**Comment by Bara** [comment]
My test server runs with sourcemod 1.10.0.6372.

I recompiled ttt.sp and ttt_sql.sp with some compiler here's the list:
1.10.0.6250 - Works.
1.10.0.6251 - Works.
1.10.0.6252 - Works.
1.10.0.6253 - Works.
1.10.0.6256 - Doesn't Work.

**Comment by Bara** [comment]
I tried this with new enum struct:

> Before we set Found - Found: 0
Before we set Found - Found: 1
[TTT] 🖕🏻 §NG Bara 🖕🏻 has found the body of Keith. It was a INNOCENT!
Before Erase - Attacker: , Victim: Keith, Found: 1
Before Erase - Index: 104 (i: 0, Length: 1)
Before Push - Attacker: , Victim: Keith, Found: 1
After Push Array: 0 (Found status: 0)

Erase and PushArray works, but it saves the old value (found = false) instead of the new value (that enum struct had before with push it).
