### ISSUE TITLE
i can't win a round with this plugin

### ISSUE THREAD

**Issue by MrCazuela** [Bara/TroubleinTerroristTown#460]
Hi
I have a multimod server (I'm new to this) and since I installed this plugin I can't win a round in "casual" with bots, the marker stays at 00:00 in a 3 minute round and it doesn't give me victory. I have a plugin that disables or activates plugins in certains maps using cvars.

**Comment by Bara** [comment]
Set `mp_ignore_round_win_conditions` to `0` and unload TTT completely in other modes. I didn't really want the "multimod support" for TTT, but it works (heard from multiple server owners). And since I don't give support for this kind of servers, so I close this issue.

If you still need support, try it on my discord server ( https://discord.gg/eCsqjcD ). This discussion exists multiple times, so use the search function.
